openapi: 3.1.0
info:
  version: 1.0.0
  title: <Contacts web app from Panther>
  license:
    name: Apache 2.0
    url: <http://www.apache.org/licenses/LICENSE-2.0.html>
  description: <Цей додаток створений для зручного користування та управління контактами з можливістю авторизації через Google та додаванням медіа-файлів до контактів>
tags:
  - name: Contacts
    description: Operations about contacts.
  - name: Auth
    description: Auth operations.

servers:
  #посилання на задеплоєний сайт
paths:
  /contacts:
    post:
      $ref: ../swagger/paths/contacts.post.yaml
  /contacts/{id}:
    get:
      $ref: '../swagger/paths/contacts/{id}/get.yaml'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
